In [1]:
# For data processing
import numpy as np
import pandas as pd

# For API usage
import requests as r

# For progress bar
from tqdm import tqdm

In [2]:
oscarData = pd.read_csv('the_oscar_award.csv')
oscarData.head()

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False

In [3]:
print("Data type : ", type(oscarData))
print("Data dims : ", oscarData.shape)

Data type :  <class 'pandas.core.frame.DataFrame'>
Data dims :  (10765, 7)

In [4]:
print(oscarData.dtypes)

year_film         int64
year_ceremony     int64
ceremony          int64
category         object
name             object
film             object
winner             bool
dtype: object

In [9]:
bestPic = oscarData[['year_film','category','film','winner']]

In [5]:
bestPic2 = oscarData[(oscarData['category'].isin(['BEST PICTURE'])) & (oscarData['winner'].isin(['TRUE']))]
print (bestPic2)

Empty DataFrame
Columns: [year_film, year_ceremony, ceremony, category, name, film, winner]
Index: []

In [34]:
winners = oscarData[oscarData['winner']]

In [37]:
bestPic2 = winners[(winners['category'] == "BEST PICTURE") | (winners['category'] == "OUTSTANDING PICTURE") | (winners['category'] == "OUTSTANDING PRODUCTION") | (winners['category'] == "OUTSTANDING MOTION PICTURE") | (winners['category'] == "BEST MOTION PICTURE")]

In [38]:
bestPic2

,year_film,year_ceremony,ceremony,category,name,film,winner
21,1927,1928,1,OUTSTANDING PICTURE,Paramount Famous Lasky,Wings,True
64,1928,1929,2,OUTSTANDING PICTURE,Metro-Goldwyn-Mayer,The Broadway Melody,True
100,1929,1930,3,OUTSTANDING PRODUCTION,Universal,All Quiet on the Western Front,True
140,1930,1931,4,OUTSTANDING PRODUCTION,RKO Radio,Cimarron,True
178,1931,1932,5,OUTSTANDING PRODUCTION,Metro-Goldwyn-Mayer,Grand Hotel,True
...,...,...,...,...,...,...,...
10219,2018,2019,91,BEST PICTURE,"Jim Burke, Charles B. Wessler, Brian Currie, P...",Green Book,True
10350,2019,2020,92,BEST PICTURE,"Kwak Sin Ae and Bong Joon Ho, Producers",Parasite,True
10474,2020,2021,93,BEST PICTURE,"Frances McDormand, Peter Spears, Mollye Asher,...",Nomadland,True
10591,2021,2022,94,BEST PICTURE,"Philippe Rousselet, Fabrice Gianfermi and Patr...",CODA,True
10718,2022,2023,95,BEST PICTURE,"Daniel Kwan, Daniel Scheinert and Jonathan Wan...",Everything Everywhere All at Once,True

In [42]:
bestPic2 = bestPic2.reset_index(drop=True)

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,OUTSTANDING PICTURE,Paramount Famous Lasky,Wings,True
1,1928,1929,2,OUTSTANDING PICTURE,Metro-Goldwyn-Mayer,The Broadway Melody,True
2,1929,1930,3,OUTSTANDING PRODUCTION,Universal,All Quiet on the Western Front,True
3,1930,1931,4,OUTSTANDING PRODUCTION,RKO Radio,Cimarron,True
4,1931,1932,5,OUTSTANDING PRODUCTION,Metro-Goldwyn-Mayer,Grand Hotel,True
...,...,...,...,...,...,...,...
90,2018,2019,91,BEST PICTURE,"Jim Burke, Charles B. Wessler, Brian Currie, P...",Green Book,True
91,2019,2020,92,BEST PICTURE,"Kwak Sin Ae and Bong Joon Ho, Producers",Parasite,True
92,2020,2021,93,BEST PICTURE,"Frances McDormand, Peter Spears, Mollye Asher,...",Nomadland,True
93,2021,2022,94,BEST PICTURE,"Philippe Rousselet, Fabrice Gianfermi and Patr...",CODA,True
94,2022,2023,95,BEST PICTURE,"Daniel Kwan, Daniel Scheinert and Jonathan Wan...",Everything Everywhere All at Once,True

In [44]:
bestPic2.to_csv('BestPicWinners.csv', index = True)